[project]
name = "matchmakinglab"
version = "0.1.0"
description = "A framework for prototyping competitive matchmaking algorithms."
authors = [{ name = "An Spiteri" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
	"click",
	"rich"
]

[project.optional-dependencies]
dev = [
    "pytest",
	"pytest-mock"
]

[project.scripts]
matchmakinglab = "matchmakinglab.app:cli"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["matchmakinglab"]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff.lint]
# Ignores F841 (Unused variable) globally
ignore = ["F841"]

[tool.pyrefly]
# Disables unused local variable warnings and hints
disable-unused-local = true
