[project]
name = "matchmakinglab"
version = "0.1.0"
description = "A framework for prototyping competitive matchmaking algorithms."
authors = [{ name = "An Spiteri" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
	"fastapi[standard]",
]

[project.optional-dependencies]
dev = [
    "pytest",
	"pytest-mock"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["matchmakinglab"]

[tool.fastapi]
entrypoint = "matchmakinglab.api:app"
